# Generated by Django 3.0.6 on 2020-05-23 08:01

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=50)),
                ('image_content', models.ImageField(upload_to=posts.models.user_directory_path)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
