# Generated by Django 3.0.6 on 2020-05-25 09:27

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200525_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_content',
            field=models.ImageField(blank=True, default='', upload_to=posts.models.user_directory_path),
            preserve_default=False,
        ),
    ]
