# Generated by Django 3.0.6 on 2020-05-25 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_auto_20200525_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_content',
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='', verbose_name='text content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=posts.models.user_directory_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_images', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='posts.Post')),
            ],
        ),
    ]
